server:
  port: '8082'

spring:
  profiles:
    active: prod

---

  spring:
    profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-dev
    password: Nep@l+977
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  welcome:
    message: Welcome to Daily code Buffer

---

  spring:
    profiles: qa
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      url: jdbc:mysql://localhost:3306/dcbapp-qa
      password: Nep@l+977
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: 'true'
  welcome:
    message: Welcome to Daily code Buffer

---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: Nep@l+977
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Daily code Buffer